/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LinksRouteImport } from './routes/links'
import { Route as PerksRouteImport } from './routes/perks'
import { Route as StoreRouteImport } from './routes/store'
import { Route as UnbanRouteImport } from './routes/unban'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const PerksRoute = PerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const UnbanRoute = UnbanRouteImport.update({
  id: '/unban',
  path: '/unban',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/links': typeof LinksRoute
  '/perks': typeof PerksRoute
  '/store': typeof StoreRoute
  '/unban': typeof UnbanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/links': typeof LinksRoute
  '/perks': typeof PerksRoute
  '/store': typeof StoreRoute
  '/unban': typeof UnbanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/links': typeof LinksRoute
  '/perks': typeof PerksRoute
  '/store': typeof StoreRoute
  '/unban': typeof UnbanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/links' | '/perks' | '/store' | '/unban'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/links' | '/perks' | '/store' | '/unban'
  id: '__root__' | '/' | '/admin' | '/links' | '/perks' | '/store' | '/unban'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LinksRoute: typeof LinksRoute
  PerksRoute: typeof PerksRoute
  StoreRoute: typeof StoreRoute
  UnbanRoute: typeof UnbanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perks': {
      id: '/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof PerksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unban': {
      id: '/unban'
      path: '/unban'
      fullPath: '/unban'
      preLoaderRoute: typeof UnbanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LinksRoute: LinksRoute,
  PerksRoute: PerksRoute,
  StoreRoute: StoreRoute,
  UnbanRoute: UnbanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
